<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="container-fluid p-5 bg-success text-white text-center">
    <h1>Дневники Онлайн</h1>
    <p>Заведи свой дневник, сохрани важные воспоминания!</p>
</div>
<div class="bg-light p-3 text-center">
    <h2>Личный кабинет</h2>
    <div class="btn-group-vertical">
        <button type="button" class="btn btn-success">Создать дневник</button>
        <button type="button" class="btn btn-success">Мои дневники</button>
        <button type="button" class="btn btn-success">
            <a href="/diaries" style="color: white;">Все дневники</a>
        </button>
        <button type="button" class="btn btn-success">
            <a href="/logout" style="color: white;">Выход</a>
        </button>
    </div>
</div>

</body>
</html>