CREATE TABLE PERSON (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(6) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);
